name: Push Actions

on:
    push:
        branches: [ main ]
    pull_request:

jobs:
  duster:
    name: 'Duster'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: "Duster Fix"
        uses: tighten/duster-action@v2
        with:
          args: fix

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Dusting
          commit_user_name: GitHub Action
          commit_user_email: actions@github.com

  static_analysis:
    name: 'Static analysis'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@master
        with:
          php-version: '8.1'

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader --ignore-platform-reqs

      - name: Execute strict static analysis via Larastan
        run: vendor/bin/phpstan analyse --configuration=phpstan.neon
